In [3]:
import numpy as np
array = np.array([1,2,3,4,5,6,8])
np.median(array)

4.0

In [4]:
np.median(array)

4.0

In [5]:
np.min(array)

1

In [6]:
np.max(array)

8

In [7]:
stv_dev = np.std(array)

In [9]:
print(stv_dev)

2.231499907401901


In [10]:
np.sum(array)

29

In [11]:
reshaped_array = array.reshape(1,7)

In [12]:
print(reshaped_array)

[[1 2 3 4 5 6 8]]


In [14]:
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])

In [16]:
concateanated = np.concatenate((array1,array))

In [17]:
print(concateanated)

[1 2 3 1 2 3 4 5 6 8]


In [18]:
numbers = np.linspace(0,10,5)

In [19]:
print(numbers)

[ 0.   2.5  5.   7.5 10. ]


In [20]:
range_data = np.arange(0,5,2)

In [21]:
print(range_data)

[0 2 4]
